[server]
# to start the daemon way
daemon=false
# configuration file specifying additional options
pid_file="/var/run/monitord.pid"
# log file
log_file="/var/log/monitord.log"
# unix socket file
unix_file="/var/run/monitord.sock"
# join token
token="b70ee310bc5bb78ced7f1f389d14da1e"
[client]
# unix socket file
unix_file="/var/run/monitor.sock"
[mongodb]
host="127.0.0.1"
port=27017
auth_db="vpn"
username="shadowsocks"
password="mlgR4evB"