[server]
# to start the daemon way
daemon=false
# configuration file specifying additional options
pid_file="/var/run/monitord.pid"
# log file
log_file="/var/log/monitord.log"
# unix socket file
unix_file="/var/run/monitord.sock"
[client]
# unix socket file
unix_file="/var/run/monitor.sock"